services:
  nova-api:
    build: .
    container_name: nova_backend
    ports:
      - "8000:8000"  # Maps port 8000 on your PC to port 8000 in the container
    volumes:
      # Notice how volumes is indented directly under ports!
      - C:/Users/Asus/Documents/TEST:/app/data/scan_root

      # (Highly recommended) Map your DB and Models so they persist!
      - ./db:/app/db
      - ./models:/app/models