"""
nova/brain/llm_engine.py

The Brain - a single local LLM (Qwen 2.5 3B or Llama 3.2 3B, GGUF,
Q4_K_M) loaded once via llama-cpp-python. Handles:
  - persona/system prompt prefix (KV-cached so it's paid for once)
  - native tool/function calling against the schemas collected by
    the ToolRouter
  - plain conversational generation when no tool applies

This is intentionally the ONLY LLM in the system (see architecture
doc "Anatomy of NOVA's Single-Brain System") - whisper.cpp and Piper
are non-LLM "organs", not separate brains.
"""
import datetime
import json
import logging
import time
import gc
import re
from typing import Optional

from nova.config import (
    LLM_MODEL_PATH,
    LLM_MODELS,
    LLM_DEFAULT_MODEL_ID,
    LLM_CONTEXT_SIZE,
    LLM_THREADS,
    LLM_GPU_LAYERS,
    NOVA_PERSONA_PROMPT,
)

logger = logging.getLogger("nova.llm_engine")
_THINKING_BLOCK = re.compile(r"<think>.*?</think>\s*", re.IGNORECASE | re.DOTALL)

try:
    from llama_cpp import Llama
    _LLAMA_CPP_AVAILABLE = True
except ImportError:  # pragma: no cover - lets the server boot before the wheel/model is installed
    _LLAMA_CPP_AVAILABLE = False


class LLMEngine:
    def __init__(self):
        self._llm: Optional["Llama"] = None
        self._loaded = False
        self._active_model_id = LLM_DEFAULT_MODEL_ID

    def list_models(self) -> list[dict]:
        return [
            {
                "id": model_id,
                "label": spec["label"],
                "installed": spec["path"].exists(),
                "active": model_id == self._active_model_id,
            }
            for model_id, spec in LLM_MODELS.items()
        ]

    def select_model(self, model_id: str) -> dict:
        if model_id not in LLM_MODELS:
            raise ValueError(f"Unknown model: {model_id}")
        model_path = LLM_MODELS[model_id]["path"]
        if not model_path.exists():
            raise FileNotFoundError(f"Model is not installed: {model_path.name}")
        if model_id == self._active_model_id and self._llm is not None:
            return {"active_model_id": model_id, "label": LLM_MODELS[model_id]["label"]}

        previous_model_id = self._active_model_id
        logger.info("Switching brain model to %s ...", LLM_MODELS[model_id]["label"])
        self._llm = None
        self._loaded = False
        gc.collect()
        self._active_model_id = model_id
        try:
            self.load()
            if self._llm is None:
                raise RuntimeError(f"Failed to load model: {model_path.name}")
        except Exception:
            logger.exception("Model switch failed; restoring %s.", LLM_MODELS[previous_model_id]["label"])
            self._llm = None
            self._loaded = False
            self._active_model_id = previous_model_id
            self.load()
            raise
        return {"active_model_id": model_id, "label": LLM_MODELS[model_id]["label"]}

    def _configure_qwen3_non_thinking_mode(self) -> None:
        """Disable Qwen3 reasoning through its Jinja chat-template argument.

        The installed llama-cpp-python API cannot pass template keyword
        arguments per request, so wrap the selected model's chat handler once
        at load time. This prevents reasoning tokens from being generated.
        """
        if self._llm is None or not self._active_model_id.startswith("qwen3-"):
            return
        try:
            from llama_cpp import llama_chat_format

            base_handler = self._llm.chat_handler
            if base_handler is None:
                chat_format = self._llm.chat_format
                base_handler = self._llm._chat_handlers.get(chat_format)  # type: ignore[attr-defined]
            if base_handler is None:
                logger.warning("Could not find Qwen3 chat handler; reasoning may remain enabled.")
                return

            def non_thinking_handler(*args, **kwargs):
                kwargs["enable_thinking"] = False
                return base_handler(*args, **kwargs)

            self._llm.chat_handler = non_thinking_handler
            logger.info("Disabled Qwen3 thinking mode.")
        except Exception:  # pragma: no cover - model responses must remain available
            logger.exception("Could not configure Qwen3 non-thinking mode.")

    @staticmethod
    def _without_thinking(content: str) -> str:
        """Hide a reasoning block if an older chat template still emits one."""
        return _THINKING_BLOCK.sub("", content).strip()

    def _generation_metrics(self, completion: dict, started_at: float, output_text: str = "") -> dict:
        """Return throughput for the output generated by one LLM request."""
        elapsed_seconds = max(time.perf_counter() - started_at, 0.001)
        usage = completion.get("usage", {})
        completion_tokens = int(usage.get("completion_tokens", 0))
        # Some llama-cpp-python chat-completion versions omit usage. Count the
        # returned text with the loaded model tokenizer so the dashboard still
        # reports a useful throughput value.
        if completion_tokens == 0 and output_text and self._llm is not None:
            try:
                completion_tokens = len(self._llm.tokenize(output_text.encode("utf-8"), add_bos=False))
            except Exception:  # pragma: no cover - metrics must never break a reply
                logger.debug("Could not tokenize generated output for metrics.", exc_info=True)
        return {
            "completion_tokens": completion_tokens,
            "elapsed_seconds": round(elapsed_seconds, 3),
            "tokens_per_second": round(completion_tokens / elapsed_seconds, 2),
        }

    def load(self) -> None:
        """
        Loads the GGUF model into RAM once. llama.cpp automatically KV-caches
        the shared system-prompt prefix across calls that share it, which is
        why the persona prompt should stay static (Tier 1 memory).
        """
        if self._loaded:
            return
        if not _LLAMA_CPP_AVAILABLE:
            logger.warning(
                "llama-cpp-python not installed - LLM engine running in STUB mode. "
                "Install requirements.txt and place a GGUF model at %s to enable real inference.",
                LLM_MODEL_PATH,
            )
            self._loaded = True
            return
        model_path = LLM_MODELS.get(self._active_model_id, {}).get("path", LLM_MODEL_PATH)
        if not model_path.exists():
            logger.warning(
                "No GGUF model found at %s - LLM engine running in STUB mode until a model is placed there.",
                model_path,
            )
            self._loaded = True
            return

        logger.info("Loading brain model from %s ...", model_path)
        self._llm = Llama(
            model_path=str(model_path),
            n_ctx=LLM_CONTEXT_SIZE,
            n_threads=LLM_THREADS,
            n_gpu_layers=LLM_GPU_LAYERS,
            verbose=False,
        )
        self._configure_qwen3_non_thinking_mode()
        self._loaded = True
        logger.info("Brain model loaded (ctx=%s, threads=%s).", LLM_CONTEXT_SIZE, LLM_THREADS)

    # ------------------------------------------------------------------
    # Tool-calling generation - used by the main pipeline in main.py
    # ------------------------------------------------------------------
    async def generate_with_tools(
        self,
        user_text: str,
        tool_schemas: list,
        memory_context: str = "",
        max_tokens: int = 256,
    ) -> dict:
        """
        Returns either:
          {"type": "tool_call", "name": ..., "arguments": {...}}
          {"type": "text", "content": "..."}
        """
        self.load()
        system_prompt = self._build_system_prompt(memory_context, tool_schemas)

        if self._llm is None:
            # STUB mode (no model loaded yet) - echo back so the pipeline is testable end-to-end.
            return {"type": "text", "content": f"[stub-brain] You said: {user_text}"}

        started_at = time.perf_counter()
        completion = self._llm.create_chat_completion(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_text},
            ],
            tools=tool_schemas,
            tool_choice="auto",
            max_tokens=max_tokens,
            temperature=0.4,
        )
        choice = completion["choices"][0]["message"]
        metrics = self._generation_metrics(
            completion,
            started_at,
            choice.get("content", "") or json.dumps(choice.get("tool_calls", [])),
        )

        tool_calls = choice.get("tool_calls")
        if tool_calls:
            call = tool_calls[0]["function"]
            try:
                arguments = json.loads(call.get("arguments", "{}"))
            except json.JSONDecodeError:
                arguments = {}
            return {
                "type": "tool_call",
                "name": call["name"],
                "arguments": arguments,
                "metrics": metrics,
            }

        return {
            "type": "text",
            "content": self._without_thinking(choice.get("content", "")),
            "metrics": metrics,
        }

    # ------------------------------------------------------------------
    # Plain generation - used for the second pass (turning a tool result
    # back into spoken confirmation) and by the memory agent.
    # ------------------------------------------------------------------
    async def generate_raw(self, system_prompt: str, user_prompt: str, max_tokens: int = 128) -> str:
        text, _metrics = await self.generate_raw_with_metrics(system_prompt, user_prompt, max_tokens)
        return text

    async def generate_raw_with_metrics(
        self, system_prompt: str, user_prompt: str, max_tokens: int = 128
    ) -> tuple[str, dict]:
        self.load()
        if self._llm is None:
            return "{}", {"completion_tokens": 0, "elapsed_seconds": 0.0, "tokens_per_second": 0.0}
        started_at = time.perf_counter()
        completion = self._llm.create_chat_completion(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            max_tokens=max_tokens,
            temperature=0.2,
        )
        text = self._without_thinking(completion["choices"][0]["message"].get("content", ""))
        return text, self._generation_metrics(completion, started_at, text)

    @staticmethod
    def _current_date_context() -> str:
        """
        Returns the current date plus a lookup table of the next 14 days'
        dates and weekday names. Small local models (e.g. Qwen3-1.7B) can
        reliably READ "Friday = 2026-08-28" off a list, but cannot reliably
        COMPUTE "today + 4 days" via arithmetic - so give them the answer
        pre-computed instead of asking them to derive it.
        """
        now = datetime.datetime.now().astimezone()
        lines = [now.strftime("Current date and time: %A, %Y-%m-%d %H:%M %z")]
        lines.append("Upcoming dates (use these directly - do not calculate offsets yourself):")
        for offset in range(14):
            day = now + datetime.timedelta(days=offset)
            label = "Today" if offset == 0 else ("Tomorrow" if offset == 1 else day.strftime("%A"))
            lines.append(f"  {label}: {day.strftime('%Y-%m-%d')}")
        return "\n".join(lines)


    @staticmethod
    def _build_system_prompt(memory_context: str, tool_schemas: list) -> str:
        parts = [NOVA_PERSONA_PROMPT, LLMEngine._current_date_context()]
        if memory_context:
            parts.append(f"Known user context: {memory_context}")
        return "\n\n".join(parts)


llm_engine = LLMEngine()